name = "rainbowsmokeofficial"
main = "src/worker.js"
compatibility_date = "2024-06-25"

[vars]
ACCESS_CODE_SALT = "replace-with-random-salt"
AI_MODEL = "@cf/meta/llama-3-8b-instruct"
AI_GATEWAY_BASE_URL = "https://gateway.ai.cloudflare.com/v1/<account_id>/<gateway_name>"

[observability]
enabled = true

[assets]
binding = "ASSETS"
directory = "./public"
html_handling = "auto-trailing-slash"
cache_control = { browser_cache_ttl = 3600, edge_cache_ttl = 86400 }

[[secrets_store_secrets]]
binding = "default_secrets_store"
store_id= "534dac0648944a0e918833c3301bd7d0"

[[kv_namespaces]]
binding = "SESSION_KV"
id = "a05f6b33421c49ce8266b363a7ed10ec"
preview_id = "TODO_REPLACE_WITH_PREVIEW_KV_ID"

[[d1_databases]]
binding = "RAINBOW_DB"
database_name = "rainbow_db"
database_id = "ece48f04-b9e9-432b-9326-a92466c80bfd"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "rainbow-media"

[durable_objects]
bindings = [
  { name = "VisitCounter", class_name = "VisitCounter" }
]

[[migrations]]
tag = "v1"
new_classes = ["VisitCounter"]
